# Generated by Django 3.1.3 on 2021-06-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0010_ahjcensusname_stateprovince'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AcceptedEdits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CommunityScore',
        ),
        migrations.RemoveField(
            model_name='user',
            name='SubmittedEdits',
        ),
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.CharField(db_column='Photo', default='', max_length=255),
        ),
    ]
