# Generated by Django 3.1.3 on 2021-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0011_auto_20210620_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NumAPICalls',
            field=models.IntegerField(db_column='NumAPICalls', default=0),
        ),
    ]
